workspace:
  base: /microservice

kind: pipeline
name: build

steps:
- name: build
  image: internal/twirp-php81-gen:build
  commands:
  - make build test clean

- name: codegen
  image: internal/twirp-php81-gen:build
  commands:
  - cp build/* /usr/local/bin
  - buf --version
  - buf mod update
  - buf generate --template buf.gen.yaml --path example

- name: lint
  image: golangci/golangci-lint:v1.38.0
  pull: if-not-exists
  commands:
  - golangci-lint run --enable-all ./...
